**ðŸ˜€Testing quantities of table:**\
Each object get a sequences of exposures, and data of same object align each other on table with labels.

In [114]:
from astropy.io import fits
hdul = fits.open('703_20230503_2B_N02033_01_0001.detf')  # open a FITS file
data = hdul[1].data  # assume the first extension is a table

In [118]:
hdul[1].header

XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / 8-bit bytes
NAXIS   =                    2 / 2-dimensional binary table
NAXIS1  =                  304 / width of table in bytes
NAXIS2  =                  120 / number of rows in table
PCOUNT  =                    0 / size of special data area
GCOUNT  =                    1 / one data group (required keyword)
TFIELDS =                   47 / number of fields in each row
TTYPE1  = 'DETS_INDEX'         / label for field   1
TFORM1  = '1J      '           / data format of field: 4-byte INTEGER
TTYPE2  = 'DETECTION_NUMBER'   / label for field   2
TFORM2  = '1J      '           / data format of field: 4-byte INTEGER
TTYPE3  = 'FRAME   '           / label for field   3
TFORM3  = '1J      '           / data format of field: 4-byte INTEGER
TTYPE4  = 'SEXTRACTOR_INDEX'   / label for field   4
TFORM4  = '1J      '           / data format of field: 4-byte INTEGER
TTYPE5  = 'TIMESTAMP'          / label for field   5
TFORM5  = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT5  = 'day     '           / physical unit of field
TTYPE6  = 'RA      '           / label for field   6
TFORM6  = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT6  = 'deg     '           / physical unit of field
TTYPE7  = 'DEC     '           / label for field   7
TFORM7  = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT7  = 'deg     '           / physical unit of field
TTYPE8  = 'PIXEL_X '           / label for field   8
TFORM8  = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT8  = 'pixel   '           / physical unit of field
TTYPE9  = 'PIXEL_Y '           / label for field   9
TFORM9  = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT9  = 'pixel   '           / physical unit of field
TTYPE10 = 'MAGNITUDE'          / label for field  10
TFORM10 = '1E      '           / data format of field: 4-byte REAL
TUNIT10 = 'mag     '           / physical unit of field
TTYPE11 = 'FWHM    '           / label for field  11
TFORM11 = '1E      '           / data format of field: 4-byte REAL
TUNIT11 = 'arcsec  '           / physical unit of field
TTYPE12 = 'PSF_ELONGATION'     / label for field  12
TFORM12 = '1E      '           / data format of field: 4-byte REAL
TUNIT12 = 'pixel   '           / physical unit of field
TTYPE13 = 'PSF_ANGLE'          / label for field  13
TFORM13 = '1E      '           / data format of field: 4-byte REAL
TUNIT13 = 'deg     '           / physical unit of field
TTYPE14 = 'RMS_ERROR'          / label for field  14
TFORM14 = '1E      '           / data format of field: 4-byte REAL
TUNIT14 = 'arcsec  '           / physical unit of field
TTYPE15 = 'SIGMA   '           / label for field  15
TFORM15 = '1E      '           / data format of field: 4-byte REAL
TUNIT15 = 'arcsec  '           / physical unit of field
TTYPE16 = 'AREA    '           / label for field  16
TFORM16 = '1J      '           / data format of field: 4-byte INTEGER
TUNIT16 = 'pixel^2 '           / physical unit of field
TTYPE17 = 'MTD_SCORE'          / label for field  17
TFORM17 = '1E      '           / data format of field: 4-byte REAL
TTYPE18 = 'VELOCITY'           / label for field  18
TFORM18 = '1E      '           / data format of field: 4-byte REAL
TUNIT18 = 'deg/day '           / physical unit of field
TTYPE19 = 'POSITION_ANGLE'     / label for field  19
TFORM19 = '1E      '           / data format of field: 4-byte REAL
TUNIT19 = 'deg     '           / physical unit of field
TTYPE20 = 'PIXELS_PER_FRAME'   / label for field  20
TFORM20 = '1E      '           / data format of field: 4-byte REAL
TUNIT20 = 'pixel   '           / physical unit of field
TTYPE21 = 'TAIL    '           / label for field  21
TFORM21 = '1E      '           / data format of field: 4-byte REAL
TUNIT21 = 'pixel   '           / physical unit of field
TTYPE22 = 'DIGEST2_SCORE'      / label for field  22
TFORM22 = '1E      '           / data format of field: 4-byte REAL
TTYPE23 = 'DET_TYPE'           / label for field  23
TFORM23 = '12A     '           / data format of field: ASCII Character
TTYPE24 = 'ERRX2WIN_IMAGE'     / label for field  24
TFORM24 = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT24 = 'pixel^2 '           / physical unit of field
TTYPE25 = 'ERRY2WIN_IMAGE'     / label for field  25
TFORM25 = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT25 = 'pixel^2 '           / physical unit of field
TTYPE26 = 'ERRXYWIN_IMAGE'     / label for field  26
TFORM26 = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT26 = 'pixel^2 '           / physical unit of field
TTYPE27 = 'HITS_ID '           / label for field  27
TFORM27 = '40A     '           / data format of field: ASCII Character
TTYPE28 = 'MPCFLAGS'           / label for field  28
TFORM28 = '1J      '           / data format of field: 4-byte INTEGER
TTYPE29 = 'IAU_NUMBER'         / label for field  29
TFORM29 = '1J      '           / data format of field: 4-byte INTEGER
TTYPE30 = 'DESIGNATION'        / label for field  30
TFORM30 = '20A     '           / data format of field: ASCII Character
TTYPE31 = 'EXTNUM  '           / label for field  31
TFORM31 = '1J      '           / data format of field: 4-byte INTEGER
TTYPE32 = 'ERRTHETAWIN_IMAGE'  / label for field  32
TFORM32 = '1E      '           / data format of field: 4-byte REAL
TUNIT32 = 'deg     '           / physical unit of field
TTYPE33 = 'FLUX_ISOCOR'        / label for field  33
TFORM33 = '1E      '           / data format of field: 4-byte REAL
TUNIT33 = 'count   '           / physical unit of field
TTYPE34 = 'FLUX_AUTO'          / label for field  34
TFORM34 = '1E      '           / data format of field: 4-byte REAL
TUNIT34 = 'count   '           / physical unit of field
TTYPE35 = 'FLUXERR_AUTO'       / label for field  35
TFORM35 = '1E      '           / data format of field: 4-byte REAL
TUNIT35 = 'count   '           / physical unit of field
TTYPE36 = 'FLUX_RADIUS'        / label for field  36
TFORM36 = '1E      '           / data format of field: 4-byte REAL
TUNIT36 = 'pixel   '           / physical unit of field
TTYPE37 = 'TEMP_DESIG'         / label for field  37
TFORM37 = '20A     '           / data format of field: ASCII Character
TTYPE38 = 'OBSERVER_MARK'      / label for field  38
TFORM38 = '1J      '           / data format of field: 4-byte INTEGER
TTYPE39 = 'DETECTION_CHECK'    / label for field  39
TFORM39 = '1J      '           / data format of field: 4-byte INTEGER
TTYPE40 = 'DETECTION_SENT'     / label for field  40
TFORM40 = '1J      '           / data format of field: 4-byte INTEGER
TTYPE41 = 'MAG_MEASURED'       / label for field  41
TFORM41 = '1E      '           / data format of field: 4-byte REAL
TUNIT41 = 'mag     '           / physical unit of field
TTYPE42 = 'RA_MEASURED'        / label for field  42
TFORM42 = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT42 = 'hour    '           / physical unit of field
TTYPE43 = 'DEC_MEASURED'       / label for field  43
TFORM43 = '1D      '           / data format of field: 8-byte DOUBLE
TUNIT43 = 'deg     '           / physical unit of field
TTYPE44 = 'MU_MAX  '           / label for field  44
TFORM44 = '1E      '           / data format of field: 4-byte REAL
TUNIT44 = 'mag/arcsec^2'       / physical unit of field
TTYPE45 = 'MU_THRESHOLD'       / label for field  45
TFORM45 = '1E      '           / data format of field: 4-byte REAL
TUNIT45 = 'mag/arcsec^2'       / physical unit of field
TTYPE46 = 'DELTAMU '           / label for field  46
TFORM46 = '1E      '           / data format of field: 4-byte REAL
TUNIT46 = 'mag/arcsec^2'       / physical unit of field
TTYPE47 = 'PRECOVERY'          / label for field  47
TFORM47 = '1J      '           / data format of field: 4-byte INTEGER
EXTNAME = 'CSS_DETS'           / name of this binary table extension
TDISP1  = 'I5      '
TDISP2  = 'I4      '
TDISP3  = 'I3      '
TDISP4  = 'I6      '
TDISP5  = 'F16.8   '
TDISP6  = 'F10.6   '
TDISP7  = 'F9.5    '
TDISP8  = 'F9.3    '
TDISP9  = 'F9.3    '
TDISP10 = 'F6.2    '
TDISP11 = 'F6.3    '
TDISP12 = 'F6.3    '
TDISP13 = 'F6.1    '
TDISP14 = 'F6.2    '
TDISP15 = 'F6.2    '
TDISP16 = 'I4      '
TDISP17 = 'F6.2    '
TDISP18 = 'F7.3    '
TDISP19 = 'F6.1    '
TDISP20 = 'F6.1    '
TDISP21 = 'F6.1    '
TDISP22 = 'F6.1    '
TDISP23 = 'A8      '
TDISP24 = 'D17.10  '
TDISP25 = 'D17.10  '
TDISP26 = 'D17.10  '
TDISP27 = 'A20     '
TDISP28 = 'Z4      '
TDISP29 = 'I6      '
TDISP30 = 'A20     '
TDISP31 = 'I3      '
TDISP32 = 'F7.3    '
TDISP33 = 'G12.7   '
TDISP34 = 'G12.7   '
TDISP35 = 'G12.7   '
TDISP36 = 'F10.3   '
TDISP37 = 'A20     '
TDISP38 = 'I3      '
TDISP39 = 'I3      '
TDISP40 = 'I3      '
TDISP41 = 'F6.2    '
TDISP42 = 'F10.6   '
TDISP43 = 'F9.5    '
TDISP44 = 'F8.4    '
TDISP45 = 'F8.4    '
TDISP46 = 'F5.2    '
TDISP47 = 'I3      '
COMMENT
COMMENT Catalina Sky Survey moving object detections
COMMENT
DETS_VER= 'DETSV2.0'           / DETS file version
NEXPOSE =                    4 / number of exposures for detections
NTOTAL  =                    4 / total exposures in field
COMMENT
ARCH1   = '703_20230503_2B_N02033_01_0001.arch.fz'
ARCH2   = '703_20230503_2B_N02033_01_0002.arch.fz'
ARCH3   = '703_20230503_2B_N02033_01_0003.arch.fz'
ARCH4   = '703_20230503_2B_N02033_01_0004.arch.fz'
COMMENT
MJD1    =     60067.1559375999 / Modified Julian Date
MJD2    =     60067.1620058301
MJD3    =     60067.1680778801
MJD4    =     60067.1741448198
COMMENT
DETMAX  =                   30 / maximum detection number
COMMENT
MPCCODE = '703     '           / Observatory code
OBSERVER= 'J. B. Fazekas'      / CSS Observer
DETECTOR= 'STA1600LN_10K'      / CCD Detector
OBJECT  = 'N02033  '           / Survey or follow-up field
FILTER  = 'NONE    '           / Filter name
TKSTACK =                    1 / Images to stack per visit
BIASRA  =                   0. / [deg/day] Telescope tracking bias RA
BIASDEC =                   0. / [deg/day] Telescope tracking bias Dec
SHUTSPDM= '        '           / [m/sec] Shutter speed
SHUTSPDP= '        '           / [pix/sec] Shutter speed
CDELT1  =        -0.0008358333 / [deg] X Pixel Size
CDELT2  =         0.0008358333 / [deg] Y Pixel Size
PIXSIZE =                3.009 / [arcsec] Pixel Size
COMMENT
VACUUM1 =                   0. / [torr] vacuum
VACUUM2 =                   0.
VACUUM3 =                   0.
VACUUM4 =                   0.
CAMTEMP1=                -110. / camera temp in centigrade
CAMTEMP2=                -110.
CAMTEMP3=               -109.9
CAMTEMP4=                -110.
FOCUS1  =                43222 / focus encoder value
FOCUS2  =                43221
FOCUS3  =                43221
FOCUS4  =                43221
COMMENT
HA1     = '+01:39:14'          / Hour angle
HA2     = '+01:47:59'
HA3     = '+01:56:46'
HA4     = '+02:05:30'
ZD1     =                 38.1 / Zenith distance
ZD2     =                 39.4
ZD3     =                 40.8
ZD4     =                 42.2
AZ1     =                222.8 / Azimuth value returned by TCS
AZ2     =                225.6
AZ3     =                228.3
AZ4     =                230.8
AIRMASS1=                 1.27 / Airmass
AIRMASS2=                 1.29
AIRMASS3=                 1.32
AIRMASS4=                 1.35
COMMENT
FLAT1   = 'mflat.703.20221106.fits' / Flatfile used to calibrate image
FLAT2   = 'mflat.703.20220214.fits'
FLAT3   = 'mflat.703.20220420.fits'
FLAT4   = 'mflat.703.20220214.fits'
COMMENT
SKYBR1  =                19.13 / [mag/arcsec^2] Night Sky Brightness
SKYBR2  =                19.08
SKYBR3  =                18.92
SKYBR4  =                19.02
DET50_1 =                 18.7 / Magnitude of expected 50% asteroid detection
DET50_2 =                18.72
DET50_3 =                18.64
DET50_4 =                18.55
DET0_1  =                19.95 / Magnitude of expected 0% asteroid detection
DET0_2  =                19.97
DET0_3  =                19.89
DET0_4  =                 19.8
MAGZP1  =               27.077 / vphot adjusted magnitude zero point
MAGZP2  =               27.029
MAGZP3  =               27.015
MAGZP4  =               27.041
VPHOFF_1=                 0.27 / vphot magnitude offset
VPHOFF_2=                0.318
VPHOFF_3=                0.332
VPHOFF_4=                0.306
VPHDEV_1=                0.281 / vphot mag solution std deviation
VPHDEV_2=                0.287
VPHDEV_3=                0.322
VPHDEV_4=                0.314
VPHCNT_1=               17906. / vphot used star count
VPHCNT_2=               17653.
VPHCNT_3=               18084.
VPHCNT_4=               17869.
COMMENT
OSHUT1  = '        '           / Shutter open dir (deg E from N, -1 radial)
OSHUT2  = '        '
OSHUT3  = '        '
OSHUT4  = '        '
CSHUT1  = '        '           / Shutter close dir (deg E from N, -1 radial)
CSHUT2  = '        '
CSHUT3  = '        '
CSHUT4  = '        '
COMMENT
DATEMID1= '2023-05-03T03:44:33.0058640' / UTC date and time of mid-exposure
DATEMID2= '2023-05-03T03:53:17.3000102'
DATEMID3= '2023-05-03T04:02:01.9245924'
DATEMID4= '2023-05-03T04:10:46.1098691'
MJDMID1 =     60067.1559375679 / [d] Measured mid-exposure
MJDMID2 =     60067.1620057872
MJDMID3 =     60067.1680778309
MJDMID4 =     60067.1741447902
EXPOSE1 =           29.9998341 / [s] Measured exposure duration
EXPOSE2 =           29.9997304
EXPOSE3 =           29.9998316
EXPOSE4 =            29.999831
COMMENT
WMATCH1 =                13495 / WCSMATCH
WMATCH2 =                13495
WMATCH3 =                13495
WMATCH4 =                13495
WCSSEP1 =                0.242 / Stddev in astrometric solution
WCSSEP2 =                0.258
WCSSEP3 =                0.283
WCSSEP4 =                 0.25
COMMENT
AIRMS1_1=         2.961979E-05 / Astrom. dispersion RMS (intern., high S/N)
AIRMS1_2=         2.961979E-05
AIRMS1_3=         2.961979E-05
AIRMS1_4=         2.961979E-05
AIRMS2_1=         2.025495E-05 / Astrom. dispersion RMS (intern., high S/N)
AIRMS2_2=         2.025495E-05
AIRMS2_3=         2.025495E-05
AIRMS2_4=         2.025495E-05
ARRMS1_1=          4.49071E-05 / Astrom. dispersion RMS (ref., high S/N)
ARRMS1_2=         4.902445E-05
ARRMS1_3=         5.380137E-05
ARRMS1_4=         4.872276E-05
ARRMS2_1=         5.014561E-05 / Astrom. dispersion RMS (ref., high S/N)
ARRMS2_2=         5.228657E-05
ARRMS2_3=         5.732864E-05
ARRMS2_4=         4.938385E-05
COMMENT
CD1_1_1 =  -0.0008356438424006 / Linear projection matrix
CD1_1_2 =  -0.0008356445900531
CD1_1_3 =  -0.0008356487901167
CD1_1_4 =  -0.0008356586944322
CD1_2_1 =  -3.804195934616E-07 / Linear projection matrix
CD1_2_2 =  -3.883367658466E-07
CD1_2_3 =   -4.07248609725E-07
CD1_2_4 =  -4.077480268594E-07
CD2_1_1 =  -5.315785549146E-07 / Linear projection matrix
CD2_1_2 =  -5.520391287837E-07
CD2_1_3 =  -5.701399130968E-07
CD2_1_4 =  -5.939536939475E-07
CD2_2_1 =   0.0008357877810948 / Linear projection matrix
CD2_2_2 =   0.0008357881381002
CD2_2_3 =   0.0008357820114355
CD2_2_4 =   0.0008357841404803
COMMENT
HISTORY header keywords updated
CHECKSUM= 'mV99nV97mV97mV97'   / HDU checksum updated 2023-05-03T11:38:05
DATASUM = '1133255458'         / data unit checksum updated 2023-05-03T11:38:05

In [148]:
data[0]

(1, 1, 1, 25164, 2460067.6559376, 9.475401, 1.05818, 1212.471, 1284.471, 16.8, 2.3, 1.245, 8.4, 0.09, 3.23, 15, 0.92, 0.223, 97.9, 1.6, 0.1, -1.0, 'ephem', 0.0010843692582446292, 0.0010845208148385238, 5.110413579217027e-10, '  (3700) Geowilliams', 7, 3700, 'Geowilliams', 1, 89.8068, 12931.325, 12138.0, 583.87256, 1.0093015, 'C3QR281', 1, -1, 1, 16.8, 9.47540000014835, 1.0581666665607028, 21.366829, 24.598656, 3.2318268, -1)

In [120]:
len(data[0])

47

In [145]:
len(data)

120

In [121]:
type(data)

astropy.io.fits.fitsrec.FITS_rec

In [123]:
hdul[1].header["MPCCODE"]

'703'

In [124]:
hdul[1].header["NEXPOSE"]

4

'DETECTION_NUMBER' same for same object,

In [125]:
data["DETECTION_NUMBER"]

array([ 1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,
        5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13,
       13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17,
       18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21, 22,
       22, 22, 22, 23, 23, 23, 23, 24, 24, 24, 24, 25, 25, 25, 25, 26, 26,
       26, 26, 27, 27, 27, 27, 28, 28, 28, 28, 29, 29, 29, 29, 30, 30, 30,
       30], dtype=int32)

'DETS_INDEX' is sequences unique ID

In [129]:
data["DETS_INDEX"]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120], dtype=int32)

In [144]:
data["DEC"][0:20] #each four data are for the same one object,
#shown this propertybelow.

array([1.05818, 1.05795, 1.05785, 1.05762, 2.9034 , 2.90784, 2.91233,
       2.91653, 2.41959, 2.41979, 2.41992, 2.42008, 3.90858, 3.90821,
       3.90802, 3.90771, 0.70395, 0.7535 , 0.80179, 0.8499 ])

**ðŸ˜€Sample procedures of convert Catalina's bintable to recovery format**

In [131]:
import pandas as pd

refer = {'dectection_offset':[0,1,2,3], 
        'exposure_mjd_mid':[hdul[1].header["MJDMID1"], hdul[1].header["MJDMID2"], hdul[1].header["MJDMID3"], hdul[1].header["MJDMID4"]],
        'exposure_duration':[hdul[1].header["EXPOSE1"], hdul[1].header["EXPOSE2"], hdul[1].header["EXPOSE3"], hdul[1].header["EXPOSE4"]],
         'mag_sigma':[hdul[1].header["VPHDEV_1"],hdul[1].header["VPHDEV_2"],hdul[1].header["VPHDEV_3"],hdul[1].header["VPHDEV_4"]]
       }
# Create DataFrame
refer_table = pd.DataFrame(refer)
refer_table['exposure_mjd_start'] = refer_table['exposure_mjd_mid'] - refer_table['exposure_duration'] /(3600*24)/2

In [132]:
refer_table

,dectection_offset,exposure_mjd_mid,exposure_duration,mag_sigma,exposure_mjd_start
0,0,60067.155938,29.999834,0.281,60067.155764
1,1,60067.162006,29.999730,0.287,60067.161832
2,2,60067.168078,29.999832,0.322,60067.167904
3,3,60067.174145,29.999831,0.314,60067.173971

In [150]:
from astropy import units as u
obs = {'obs_index' : data["DETS_INDEX"],
       'dectection_offset' : (data["DETS_INDEX"] - 1)% 4 ,
        'mjd' : data["TIMESTAMP"] - 2400000.5,
        'ra' : data["RA"],
        'dec' : data["Dec"],
        'ra_sigma' : data["SIGMA"] * u.arcsec.to(u.deg),
        'dec_sigma' : data["SIGMA"] * u.arcsec.to(u.deg),
        'mag' : data["MAGNITUDE"] }
        #'mag_sigma' : data["DELTAMU"]
obs_table = pd.DataFrame(obs)
obs_table = obs_table.astype({"obs_index": str}, errors='raise') 
obs_table[["ra", "dec"]] = obs_table[["ra", "dec"]].apply(pd.to_numeric)

In [151]:
obs_table

,obs_index,dectection_offset,mjd,ra,dec,ra_sigma,dec_sigma,mag
0,1,0,60067.155938,9.475401,1.05818,0.000897,0.000897,16.799999
1,2,1,60067.162006,9.475494,1.05795,0.001003,0.001003,16.709999
2,3,2,60067.168078,9.475584,1.05785,0.000925,0.000925,16.629999
3,4,3,60067.174145,9.475669,1.05762,0.000847,0.000847,16.870001
4,5,0,60067.155938,9.370969,2.90340,0.000553,0.000553,17.910000
...,...,...,...,...,...,...,...,...
115,116,3,60067.174145,9.528617,0.32838,0.000333,0.000333,18.610001
116,117,0,60067.155938,9.250466,0.02067,0.000000,0.000000,0.000000
117,118,1,60067.162006,9.250529,0.02847,0.000586,0.000586,18.180000
118,119,2,60067.168078,9.250605,0.03643,0.001039,0.001039,0.000000
119,120,3,60067.174145,9.250654,0.04407,0.000792,0.000792,17.590000

In [152]:
final_table = pd.merge(obs_table,refer_table, on = 'dectection_offset', how='left')

In [153]:
final_table

,obs_index,dectection_offset,mjd,ra,dec,ra_sigma,dec_sigma,mag,exposure_mjd_mid,exposure_duration,mag_sigma,exposure_mjd_start
0,1,0,60067.155938,9.475401,1.05818,0.000897,0.000897,16.799999,60067.155938,29.999834,0.281,60067.155764
1,2,1,60067.162006,9.475494,1.05795,0.001003,0.001003,16.709999,60067.162006,29.999730,0.287,60067.161832
2,3,2,60067.168078,9.475584,1.05785,0.000925,0.000925,16.629999,60067.168078,29.999832,0.322,60067.167904
3,4,3,60067.174145,9.475669,1.05762,0.000847,0.000847,16.870001,60067.174145,29.999831,0.314,60067.173971
4,5,0,60067.155938,9.370969,2.90340,0.000553,0.000553,17.910000,60067.155938,29.999834,0.281,60067.155764
...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,3,60067.174145,9.528617,0.32838,0.000333,0.000333,18.610001,60067.174145,29.999831,0.314,60067.173971
116,117,0,60067.155938,9.250466,0.02067,0.000000,0.000000,0.000000,60067.155938,29.999834,0.281,60067.155764
117,118,1,60067.162006,9.250529,0.02847,0.000586,0.000586,18.180000,60067.162006,29.999730,0.287,60067.161832
118,119,2,60067.168078,9.250605,0.03643,0.001039,0.001039,0.000000,60067.168078,29.999832,0.322,60067.167904
119,120,3,60067.174145,9.250654,0.04407,0.000792,0.000792,17.590000,60067.174145,29.999831,0.314,60067.173971

In [154]:
final_table['exposure_id'] = '703_20230503_2B_N02033_01_0001'
final_table = final_table.astype({"dectection_offset": str}, errors='raise') 
final_table['obs_id'] = final_table['exposure_id'] +"_" + final_table['obs_index'] +"_"+ final_table['dectection_offset']
final_table['observatory_code'] =  hdul[1].header["MPCCODE"]
final_table['filter'] =  hdul[1].header["FILTER"]

In [155]:
final_table

,obs_index,dectection_offset,mjd,ra,dec,ra_sigma,dec_sigma,mag,exposure_mjd_mid,exposure_duration,mag_sigma,exposure_mjd_start,exposure_id,obs_id,observatory_code,filter
0,1,0,60067.155938,9.475401,1.05818,0.000897,0.000897,16.799999,60067.155938,29.999834,0.281,60067.155764,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_1_0,703,NONE
1,2,1,60067.162006,9.475494,1.05795,0.001003,0.001003,16.709999,60067.162006,29.999730,0.287,60067.161832,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_2_1,703,NONE
2,3,2,60067.168078,9.475584,1.05785,0.000925,0.000925,16.629999,60067.168078,29.999832,0.322,60067.167904,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_3_2,703,NONE
3,4,3,60067.174145,9.475669,1.05762,0.000847,0.000847,16.870001,60067.174145,29.999831,0.314,60067.173971,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_4_3,703,NONE
4,5,0,60067.155938,9.370969,2.90340,0.000553,0.000553,17.910000,60067.155938,29.999834,0.281,60067.155764,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_5_0,703,NONE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,3,60067.174145,9.528617,0.32838,0.000333,0.000333,18.610001,60067.174145,29.999831,0.314,60067.173971,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_116_3,703,NONE
116,117,0,60067.155938,9.250466,0.02067,0.000000,0.000000,0.000000,60067.155938,29.999834,0.281,60067.155764,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_117_0,703,NONE
117,118,1,60067.162006,9.250529,0.02847,0.000586,0.000586,18.180000,60067.162006,29.999730,0.287,60067.161832,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_118_1,703,NONE
118,119,2,60067.168078,9.250605,0.03643,0.001039,0.001039,0.000000,60067.168078,29.999832,0.322,60067.167904,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_119_2,703,NONE
119,120,3,60067.174145,9.250654,0.04407,0.000792,0.000792,17.590000,60067.174145,29.999831,0.314,60067.173971,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_120_3,703,NONE

In [156]:
final_table = final_table.drop(columns=['obs_index'])
final_table = final_table.drop(columns=['dectection_offset'])

final_table = final_table.astype({"exposure_id": str}, errors='raise')
final_table = final_table.astype({"obs_id": str}, errors='raise') 
final_table = final_table.astype({"observatory_code": str}, errors='raise') 
final_table = final_table.astype({"filter": str}, errors='raise')

In [157]:
final_table

,mjd,ra,dec,ra_sigma,dec_sigma,mag,exposure_mjd_mid,exposure_duration,mag_sigma,exposure_mjd_start,exposure_id,obs_id,observatory_code,filter
0,60067.155938,9.475401,1.05818,0.000897,0.000897,16.799999,60067.155938,29.999834,0.281,60067.155764,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_1_0,703,NONE
1,60067.162006,9.475494,1.05795,0.001003,0.001003,16.709999,60067.162006,29.999730,0.287,60067.161832,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_2_1,703,NONE
2,60067.168078,9.475584,1.05785,0.000925,0.000925,16.629999,60067.168078,29.999832,0.322,60067.167904,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_3_2,703,NONE
3,60067.174145,9.475669,1.05762,0.000847,0.000847,16.870001,60067.174145,29.999831,0.314,60067.173971,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_4_3,703,NONE
4,60067.155938,9.370969,2.90340,0.000553,0.000553,17.910000,60067.155938,29.999834,0.281,60067.155764,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_5_0,703,NONE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,60067.174145,9.528617,0.32838,0.000333,0.000333,18.610001,60067.174145,29.999831,0.314,60067.173971,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_116_3,703,NONE
116,60067.155938,9.250466,0.02067,0.000000,0.000000,0.000000,60067.155938,29.999834,0.281,60067.155764,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_117_0,703,NONE
117,60067.162006,9.250529,0.02847,0.000586,0.000586,18.180000,60067.162006,29.999730,0.287,60067.161832,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_118_1,703,NONE
118,60067.168078,9.250605,0.03643,0.001039,0.001039,0.000000,60067.168078,29.999832,0.322,60067.167904,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_119_2,703,NONE
119,60067.174145,9.250654,0.04407,0.000792,0.000792,17.590000,60067.174145,29.999831,0.314,60067.173971,703_20230503_2B_N02033_01_0001,703_20230503_2B_N02033_01_0001_120_3,703,NONE